apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
  - name: "api-gateway"
    port: 8080
    nodePort: 31006
    targetPort: 8080
  selector:
    app: api-gateway
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: bachelor/api-gateway:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}