apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-iot
    version: v1
  name: ms-iot
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ms-iot
  template:
    metadata:
      labels:
        app: ms-iot
        version: v1
    spec:
      containers:
      - name: ms-iot
        image: bachelor/ms-iot:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}