apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-prediction
    version: v1
  name: ms-prediction
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ms-prediction
  template:
    metadata:
      labels:
        app: ms-prediction
        version: v1
    spec:
      containers:
      - name: ms-prediction
        image: bachelor/ms-prediction:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}