apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-fog
  name: ms-fog
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ms-fog
  template:
    metadata:
      labels:
        app: ms-fog
    spec:
      containers:
      - name: ms-fog
        image: bachelor/ms-fog:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-fog
  name: ms-fog
spec:
  type: NodePort
  ports:
  - name: "ms-fog"
    port: 8080
    nodePort: 31001
    targetPort: 8080
  selector:
    app: ms-fog
status:
  loadBalancer: {}

