apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-iot
  name: ms-iot
spec:
  type: NodePort
  ports:
  - name: "ms-iot"
    port: 8080
    nodePort: 31000
    targetPort: 8080
  selector:
    app: ms-iot
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-iot
  name: ms-iot
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ms-iot
  template:
    metadata:
      labels:
        app: ms-iot
    spec:
      containers:
      - name: ms-iot
        image: bachelor/ms-iot:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}