apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-prediction
  name: ms-prediction
spec:
  type: NodePort
  ports:
  - name: "ms-prediction"
    port: 8080
    nodePort: 31003
    targetPort: 8080
  selector:
    app: ms-prediction
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-prediction
    version: v1
  name: ms-prediction-1
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ms-prediction
  template:
    metadata:
      labels:
        app: ms-prediction
        version: v1
    spec:
      containers:
      - name: ms-prediction
        image: bachelor/ms-prediction:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-prediction
    version: v2
  name: ms-prediction-2
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: ms-prediction
  template:
    metadata:
      labels:
        app: ms-prediction
        version: v2
    spec:
      containers:
      - name: ms-prediction
        image: bachelor/ms-prediction-advanced:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}