apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-fog
  name: ms-fog
spec:
  type: NodePort
  ports:
  - name: "ms-fog"
    port: 8080
    nodePort: 31001
    targetPort: 8080
  selector:
    app: ms-fog
status:
  loadBalancer: {}