apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-anomaly-detection
  name: ms-anomaly-detection
spec:
  type: NodePort
  ports:
  - name: "ms-anomaly-detection"
    port: 8080
    nodePort: 31002
    targetPort: 8080
  selector:
    app: ms-anomaly-detection
status:
  loadBalancer: {}