apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-iot
  name: ms-iot
spec:
  type: NodePort
  ports:
  - name: "ms-iot"
    port: 8080
    nodePort: 31000
    targetPort: 8080
  selector:
    app: ms-iot
status:
  loadBalancer: {}