apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
    version: v1
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: bachelor/api-gateway:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}