apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
  - name: "api-gateway"
    port: 8080
    nodePort: 31006
    targetPort: 8080
  selector:
    app: api-gateway
status:
  loadBalancer: {}